dubbo:
    application:
        name: user-service
    monitor:
        protocol: registry
    protocol:
        name: dubbo
        port: 20881
    registry:
        address: 127.0.0.1:2181
        protocol: zookeeper
    scan:
      base-packages: com.a.platform
